name: Update Supervisor - Collaborator 2

on:
  repository_dispatch:
    types: [update_supervisor_collab2]

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: ./supervisor-update-collab-2

jobs:
  update-supervisor:
    if: github.event.client_payload.agent_id == secrets.COLLABORATOR_2_ID
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=supervisor-update-collab2/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Create tfvars file
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          cat > terraform.tfvars <<EOF
          supervisor_id = "${{ secrets.SUPERVISOR_ID }}"
          collaborator_id = "${{ github.event.client_payload.agent_id }}"
          new_alias_id = "${{ github.event.client_payload.new_alias_id }}"
          EOF

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve
